/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import Target from './Target.jsx';

const HumanBody = (props) => {
    const { nodes, materials } = useGLTF('/threejs/models/human_body.glb');

    return (
        <group {...props} dispose={null} nodes={nodes} materials={materials}>
            <group>
                <group rotation={[-Math.PI / 2, 0, 0]}>
                    <group rotation={[Math.PI / 2, 0, 0]}>
                        <group>
                            <group>
                                <group>
                                    <mesh
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Floor_Floor_0.geometry}
                                        material={materials.Floor}
                                    />
                                </group>
                                <group position={[0, 1.807, 0.055]} />
                                <group rotation={[-Math.PI / 2, 0, 0]} />
                            </group>
                        </group>
                    </group>
                </group>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_9.geometry}
                    material={materials.Sycranian}
                />
                <group position={[0, 1.807, 0.055]} />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.p1.geometry}
                    material={materials.redDot}
                    position={[0.14, 1.734, 0.068]}
                    scale={0.05}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.p2.geometry}
                    material={materials['redDot.001']}
                    position={[-0.141, 1.734, 0.068]}
                    scale={0.05}
                />
            </group>
            <Target position={[1,0,0]} scale={.25}/>
        </group>
    )
}

useGLTF.preload('/threejs/models/human_body.glb')
export default HumanBody;

